# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='defintion',
            new_name='definition',
        ),
    ]
