# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20170930_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='pinyin',
        ),
        migrations.RemoveField(
            model_name='word',
            name='simplified',
        ),
        migrations.RemoveField(
            model_name='word',
            name='traditional',
        ),
        migrations.AddField(
            model_name='word',
            name='hsk_level',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='word',
            name='numbered_pinyin',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='simplified_chinese',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='tonal_pinyin',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='traditional_chinese',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.CharField(max_length=360),
        ),
    ]
