# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20170930_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
